export const RIDERS = [
  { id: 1, name: "John Doe", rating: 4.8, deliveries: "1,250+", eta: "5 min" },
  {
    id: 2,
    name: "Sarah Johnson",
    rating: 4.9,
    deliveries: "980+",
    eta: "7 min",
  },
  {
    id: 3,
    name: "Michael Smith",
    rating: 4.7,
    deliveries: "1,540+",
    eta: "6 min",
  },
  { id: 4, name: "Emily Davis", rating: 4.6, deliveries: "800+", eta: "8 min" },
  {
    id: 5,
    name: "James Wilson",
    rating: 4.8,
    deliveries: "1,120+",
    eta: "4 min",
  },
  {
    id: 6,
    name: "Sophia Brown",
    rating: 4.9,
    deliveries: "1,300+",
    eta: "9 min",
  },
  { id: 7, name: "Daniel Lee", rating: 4.5, deliveries: "700+", eta: "10 min" },
  {
    id: 8,
    name: "Olivia Martinez",
    rating: 4.7,
    deliveries: "1,050+",
    eta: "6 min",
  },
  {
    id: 9,
    name: "William Anderson",
    rating: 4.6,
    deliveries: "950+",
    eta: "5 min",
  },
  {
    id: 10,
    name: "Ava Thompson",
    rating: 4.8,
    deliveries: "1,400+",
    eta: "7 min",
  },
];
